// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlwspxbxvqqqwrbjhujp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sd3NweGJ4dnFxcXdyYmpodWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTY3ODUsImV4cCI6MjA2OTkzMjc4NX0.SXkx5w37XKeBSopk-HCiJkoY13tgjZJSDc-oVz0dfxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});